name: publish-to-npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  'Bump version'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording:  'MAJOR,major,Major'
          minor-wording:  'Add,add,Adds,adds'
          patch-wording:  'Patch,patch,Patches,patches,Fixes,fixes,Fix,fix'
          rc-wording:     'ALPHA,Alpha,alpha,BETA,Beta,beta'
          default:        patch
          tag-prefix:     'v'
          commit-message: 'CI: bump version to {{version}}'
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          npm install
          npm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}